version: "3.1"

services:
   db:
      image: postgres
      restart: always
      environment:
         - POSTGRES_USER=admin
         - POSTGRES_PASSWORD=secret
         - POSTGRES_DB=routinetactics
      ports:
         - 5432:5432
